import { User, Lead, Application, Task, Payment, Teacher } from "@/types/crm";

export const TAMIL_NADU_DISTRICTS = [
  "Ariyalur",
  "Chengalpattu",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kancheepuram",
  "Kanniyakumari",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Mayiladuthurai",
  "Nagapattinam",
  "Namakkal",
  "Nilgiris",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Ranipet",
  "Salem",
  "Sivaganga",
  "Tenkasi",
  "Thanjavur",
  "Theni",
  "Thoothukudi",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Vellore",
  "Viluppuram",
  "Virudhunagar",
];

export const MOCK_ADMIN_USER: User = {
  id: "usr_admin_vsb",
  name: "VSB Admission Admin",
  email: "admin@vsb",
  role: "ADMIN",
  createdAt: new Date().toISOString(),
};

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: "tch_101",
    name: "Dr. K. Arulmurugan",
    email: "arulmurugan.cse@vsb.ac.in",
    phone: "+91 98424 11223",
    department: "Computer Science & Engineering",
    campus: "KARUR",
    coursesAssigned: ["B.E. Computer Science", "B.Tech AI & Data Science"],
    experienceYears: 14,
    status: "ACTIVE",
    avatar: "KA",
    assignedQuota: 1000,
    contactedCount: 142,
  },
  {
    id: "tch_102",
    name: "Dr. S. Meenakshi",
    email: "meenakshi.ece@vsb.ac.in",
    phone: "+91 97888 22334",
    department: "Electronics & Communication Engg",
    campus: "COIMBATORE",
    coursesAssigned: ["B.E. Electronics & Communication", "B.Tech Cyber Security"],
    experienceYears: 11,
    status: "ACTIVE",
    avatar: "SM",
    assignedQuota: 1000,
    contactedCount: 215,
  },
  {
    id: "tch_103",
    name: "Prof. P. Rajesh",
    email: "rajesh.mech@vsb.ac.in",
    phone: "+91 99433 33445",
    department: "Mechanical Engineering",
    campus: "KARUR",
    coursesAssigned: ["B.E. Mechanical Engineering"],
    experienceYears: 16,
    status: "ACTIVE",
    avatar: "PR",
    assignedQuota: 500,
    contactedCount: 88,
  },
  {
    id: "tch_104",
    name: "Dr. N. Gayathri",
    email: "gayathri.it@vsb.ac.in",
    phone: "+91 98655 44556",
    department: "Information Technology",
    campus: "COIMBATORE",
    coursesAssigned: ["B.Tech Information Technology"],
    experienceYears: 9,
    status: "ON_LEAVE",
    avatar: "NG",
    assignedQuota: 500,
    contactedCount: 64,
  },
];

export const MOCK_LEADS: (Lead & { application: Application })[] = [
  {
    id: "lead_revathy",
    name: "Revathy",
    email: "revathy@gmail.com",
    phone: "+91-9566207732",
    source: "Organic",
    courseInterest: "B.E. Computer Science and Engineering",
    campus: "KARUR",
    state: "Tamil Nadu",
    district: "Karur",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_revathy",
      leadId: "lead_revathy",
      stage: "INQUIRY",
      marks10th: 88.0,
      marks12th: 90.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_gunal",
    name: "Gunal",
    email: "gunal@gmail.com",
    phone: "+91-9551082291",
    source: "Organic",
    courseInterest: "B.E Mechanical Engineering",
    campus: "KARUR",
    state: "Tamil Nadu",
    district: "Karur",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_gunal",
      leadId: "lead_gunal",
      stage: "INQUIRY",
      marks10th: 82.0,
      marks12th: 84.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_manivel",
    name: "Manivel",
    email: "manivel@gmail.com",
    phone: "+91-8883158493",
    source: "Organic",
    courseInterest: "B.E Electrical and Electronics Engineering",
    campus: "KARUR",
    state: "Tamil Nadu",
    district: "Karur",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_manivel",
      leadId: "lead_manivel",
      stage: "INQUIRY",
      marks10th: 80.0,
      marks12th: 83.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_rajpriyan",
    name: "Raj Priyan",
    email: "rajpriyan@gmail.com",
    phone: "+91-9894283561",
    source: "Organic",
    courseInterest: "B.E Electronics and Communication Engineering",
    campus: "KARUR",
    state: "Tamil Nadu",
    district: "Karur",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_rajpriyan",
      leadId: "lead_rajpriyan",
      stage: "INQUIRY",
      marks10th: 89.0,
      marks12th: 91.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_101",
    name: "S. Vignesh",
    email: "vignesh.s@gmail.com",
    phone: "+91 98765 43210",
    source: "TNEA Counselling",
    courseInterest: "B.E. Computer Science",
    campus: "KARUR",
    school: "Govt Higher Secondary School, Karur",
    district: "Karur",
    state: "Tamil Nadu",
    address: "42 West Car Street, Karur Town, Tamil Nadu 639001",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61201",
    tneaCutoff: 194.5,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 2840,
    createdAt: "2026-08-12T10:15:00Z",
    application: {
      id: "app_201",
      leadId: "lead_101",
      stage: "FEE_PAID",
      marks10th: 94.5,
      marks12th: 96.8,
      paymentStatus: "COMPLETED",
    },
  },
  {
    id: "lead_jaikaviesh",
    name: "Jaikaviesh",
    email: "jaikaviesh.p@gmail.com",
    phone: "+91-9629693794",
    fatherName: "K. Ramachandran",
    motherName: "R. Priya",
    gender: "Male",
    bloodGroup: "O+",
    physicallyDisabled: "No",
    community: "BC",
    source: "Organic Search",
    courseInterest: "B.Tech AI & Data Science",
    campus: "KARUR",
    school: "Govt Higher Secondary School, Salem",
    district: "Salem",
    state: "Tamil Nadu",
    address: "14 West Car Street, Salem, Tamil Nadu 636001",
    status: "NEW",
    subStage: "Asked to Call Back",
    leadScore: 5,
    counselorId: "usr_admin_vsb",
    assignedTo: "Dr Dhanabal M Assistant Professor MECH",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-670B5",
    tneaCutoff: 188.5,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 3120,
    createdAt: "2026-08-11T11:38:00Z",
    application: {
      id: "app_jaikaviesh",
      leadId: "lead_jaikaviesh",
      stage: "INQUIRY",
      marks10th: 92.0,
      marks12th: 94.2,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_wilsonrani",
    name: "Wilsonrani789",
    email: "wilsonrani@gmail.com",
    phone: "+91-9585228382",
    source: "Organic",
    courseInterest: "B.Tech Information Technology",
    campus: "COIMBATORE",
    state: "Tamil Nadu",
    district: "Coimbatore",
    status: "NEW",
    createdAt: "2026-08-11T11:40:00Z",
    application: {
      id: "app_wilsonrani",
      leadId: "lead_wilsonrani",
      stage: "INQUIRY",
      marks10th: 85.0,
      marks12th: 87.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_sankari",
    name: "Sankari",
    email: "sankari@gmail.com",
    phone: "+91-9790181878",
    source: "Organic",
    courseInterest: "B.Tech Artificial Intelligence and Data Science",
    campus: "COIMBATORE",
    state: "Tamil Nadu",
    district: "Coimbatore",
    status: "NEW",
    createdAt: "2026-08-11T11:40:00Z",
    application: {
      id: "app_sankari",
      leadId: "lead_sankari",
      stage: "INQUIRY",
      marks10th: 90.0,
      marks12th: 92.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_102",
    name: "P. Ananya",
    email: "ananya.p@outlook.com",
    phone: "+91 97654 32109",
    source: "Management Quota Direct",
    courseInterest: "B.Tech AI & Data Science",
    campus: "COIMBATORE",
    school: "St. Joseph Higher Secondary School, Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "108 Trichy Road, Singanallur, Coimbatore 641005",
    status: "IN_REVIEW",
    counselorId: "usr_admin_vsb",
    assignedTo: "teachercovai@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-71409",
    tneaCutoff: 187.0,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 5120,
    createdAt: "2026-08-10T14:30:00Z",
    application: {
      id: "app_202",
      leadId: "lead_102",
      stage: "DOCS_VERIFIED",
      marks10th: 91.0,
      marks12th: 93.2,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_103",
    name: "M. Karthik",
    email: "karthik.m@yahoo.com",
    phone: "+91 96543 21098",
    source: "College Expo Salem",
    courseInterest: "B.E. Electronics & Communication",
    campus: "KARUR",
    school: "Sri Vidya Mandir Higher Sec School, Salem",
    district: "Salem",
    state: "Tamil Nadu",
    address: "15 Fairlands Main Road, Salem 636016",
    status: "CONTACTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61244",
    tneaCutoff: 176.5,
    counsellingCategory: "7.5% Govt School Quota",
    generalRank: 9410,
    createdAt: "2026-08-10T09:00:00Z",
    application: {
      id: "app_203",
      leadId: "lead_103",
      stage: "SUBMITTED",
      marks10th: 85.4,
      marks12th: 88.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_104",
    name: "R. Priyadarshini",
    email: "priya.r@techmail.in",
    phone: "+91 95432 10987",
    source: "Official VSB Portal",
    courseInterest: "B.Tech Information Technology",
    campus: "COIMBATORE",
    school: "Holy Cross Higher Sec School, Tiruchirappalli",
    district: "Tiruchirappalli",
    state: "Tamil Nadu",
    address: "88 Cantonment Main Street, Trichy 620001",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teachercovai@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-71422",
    tneaCutoff: 195.0,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 1950,
    createdAt: "2026-08-09T11:45:00Z",
    application: {
      id: "app_204",
      leadId: "lead_104",
      stage: "OFFER_ISSUED",
      marks10th: 96.0,
      marks12th: 97.5,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_105",
    name: "K. Tamilselvan",
    email: "tamil.k@gmail.com",
    phone: "+91 94321 09876",
    source: "TNEA Referral",
    courseInterest: "B.E. Mechanical Engineering",
    campus: "KARUR",
    school: "Govt Boys Model HSS, Namakkal",
    district: "Namakkal",
    state: "Tamil Nadu",
    address: "24 Mohanur Road, Namakkal 637001",
    status: "NEW",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61299",
    tneaCutoff: 169.0,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 14200,
    createdAt: "2026-08-09T16:20:00Z",
    application: {
      id: "app_205",
      leadId: "lead_105",
      stage: "INQUIRY",
      marks10th: 82.0,
      marks12th: 84.5,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_106",
    name: "S. Kaviya",
    email: "kaviya.s@domain.com",
    phone: "+91 93210 98765",
    source: "Newspaper Ad",
    courseInterest: "B.Tech Cyber Security",
    campus: "COIMBATORE",
    school: "Kongu Vellalar Matric HSS, Erode",
    district: "Erode",
    state: "Tamil Nadu",
    address: "67 Perundurai Road, Erode 638011",
    status: "IN_REVIEW",
    counselorId: "usr_admin_vsb",
    appliedCounselling: false,
    counsellingCategory: "Management Quota Direct",
    tneaCutoff: 182.2,
    createdAt: "2026-08-08T17:10:00Z",
    application: {
      id: "app_206",
      leadId: "lead_106",
      stage: "DOCS_VERIFIED",
      marks10th: 89.2,
      marks12th: 91.1,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_107",
    name: "G. Hariharan",
    email: "hari.g@outlook.com",
    phone: "+91 92109 87654",
    source: "TNEA Counselling",
    courseInterest: "B.E. Computer Science",
    campus: "COIMBATORE",
    school: "TVS Higher Secondary School, Madurai",
    district: "Madurai",
    state: "Tamil Nadu",
    address: "12 Subramaniapuram 1st Street, Madurai 625011",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-71450",
    tneaCutoff: 193.8,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 3110,
    createdAt: "2026-08-08T08:30:00Z",
    application: {
      id: "app_207",
      leadId: "lead_107",
      stage: "FEE_PAID",
      marks10th: 95.1,
      marks12th: 96.8,
      paymentStatus: "COMPLETED",
    },
  },
  {
    id: "lead_108",
    name: "A. Balaji",
    email: "balaji.a@gmail.com",
    phone: "+91 91098 76543",
    source: "College Expo Salem",
    courseInterest: "B.E Civil Engineering",
    campus: "KARUR",
    school: "Govt Boys Higher Sec School, Salem",
    district: "Salem",
    state: "Tamil Nadu",
    address: "45 Junction Road, Salem 636005",
    status: "REJECTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61311",
    tneaCutoff: 142.0,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 24500,
    createdAt: "2026-08-07T11:20:00Z",
    application: {
      id: "app_208",
      leadId: "lead_108",
      stage: "INQUIRY",
      marks10th: 71.0,
      marks12th: 71.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_109",
    name: "N. Dharshini",
    email: "dharshini.n@gmail.com",
    phone: "+91 90987 65432",
    source: "TNEA Counselling",
    courseInterest: "B.Tech Artificial Intelligence and Data Science",
    campus: "KARUR",
    school: "Paramathi Velur HSS, Namakkal",
    district: "Namakkal",
    state: "Tamil Nadu",
    address: "18 Main Road, Paramathi Velur, Namakkal 638182",
    status: "NEW",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61380",
    tneaCutoff: 191.2,
    counsellingCategory: "7.5% Govt School Quota",
    generalRank: 4120,
    createdAt: "2026-08-07T09:10:00Z",
    application: {
      id: "app_209",
      leadId: "lead_109",
      stage: "INQUIRY",
      marks10th: 93.5,
      marks12th: 95.6,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_110",
    name: "V. Gokulakrishnan",
    email: "gokul.v@outlook.com",
    phone: "+91 89876 54321",
    source: "Official VSB Portal",
    courseInterest: "B.E Electronics and Communication Engineering",
    campus: "COIMBATORE",
    school: "Bharathi Matric HSS, Coimbatore",
    district: "Coimbatore",
    state: "Tamil Nadu",
    address: "55 Avinashi Road, Peelamedu, Coimbatore 641004",
    status: "CONTACTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teachercovai@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-71488",
    tneaCutoff: 188.5,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 4890,
    createdAt: "2026-08-06T14:45:00Z",
    application: {
      id: "app_210",
      leadId: "lead_110",
      stage: "SUBMITTED",
      marks10th: 90.0,
      marks12th: 94.2,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_111",
    name: "K. Kowsalya",
    email: "kowsalya.k@gmail.com",
    phone: "+91-9842154321",
    source: "TNEA Counselling",
    courseInterest: "B.E. Computer Science and Engineering",
    campus: "KARUR",
    school: "St. Marys Girls HSS, Dindigul",
    district: "Dindigul",
    state: "Tamil Nadu",
    address: "78 Palani Road, Dindigul 624001",
    status: "NEW",
    createdAt: "2026-08-06T10:00:00Z",
    application: {
      id: "app_211",
      leadId: "lead_111",
      stage: "INQUIRY",
      marks10th: 87.5,
      marks12th: 89.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_112",
    name: "Nithish Kumar",
    email: "nithish.k@gmail.com",
    phone: "+91-9789012345",
    source: "Google Search",
    courseInterest: "B.Tech Artificial Intelligence and Data Science",
    campus: "COIMBATORE",
    school: "DAV Boys Senior Sec School, Chennai",
    district: "Chennai",
    state: "Tamil Nadu",
    address: "21 Anna Salai, Guindy, Chennai 600032",
    status: "ADMITTED",
    createdAt: "2026-08-05T12:20:00Z",
    application: {
      id: "app_212",
      leadId: "lead_112",
      stage: "FEE_PAID",
      marks10th: 95.0,
      marks12th: 97.2,
      paymentStatus: "COMPLETED",
    },
  },
  {
    id: "lead_113",
    name: "R. Soundarya",
    email: "soundarya.r@gmail.com",
    phone: "+91-9678901234",
    source: "Education Fair",
    courseInterest: "B.Tech Information Technology",
    campus: "KARUR",
    school: "Sacred Heart Girls HSS, Thanjavur",
    district: "Thanjavur",
    state: "Tamil Nadu",
    address: "34 Medical College Road, Thanjavur 613004",
    status: "CONTACTED",
    createdAt: "2026-08-05T09:15:00Z",
    application: {
      id: "app_213",
      leadId: "lead_113",
      stage: "SUBMITTED",
      marks10th: 88.4,
      marks12th: 90.8,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_114",
    name: "M. Praveen",
    email: "praveen.m@gmail.com",
    phone: "+91-9567890123",
    source: "Direct Entry",
    courseInterest: "B.E. Mechanical Engineering",
    campus: "KARUR",
    school: "KSC Govt Boys HSS, Tiruppur",
    district: "Tiruppur",
    state: "Tamil Nadu",
    address: "19 Avinashi Main Road, Tiruppur 641602",
    status: "IN_REVIEW",
    createdAt: "2026-08-04T15:30:00Z",
    application: {
      id: "app_214",
      leadId: "lead_114",
      stage: "DOCS_VERIFIED",
      marks10th: 84.0,
      marks12th: 86.5,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_115",
    name: "S. Divya",
    email: "divya.s@gmail.com",
    phone: "+91-9456789012",
    source: "TNEA Counselling",
    courseInterest: "B.E Electrical and Electronics Engineering",
    campus: "COIMBATORE",
    school: "Voorhees Higher Sec School, Vellore",
    district: "Vellore",
    state: "Tamil Nadu",
    address: "52 Katpadi Road, Vellore 632004",
    status: "NEW",
    createdAt: "2026-08-04T11:00:00Z",
    application: {
      id: "app_215",
      leadId: "lead_115",
      stage: "INQUIRY",
      marks10th: 89.0,
      marks12th: 91.5,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_116",
    name: "K. Abinaya",
    email: "abinaya.k@gmail.com",
    phone: "+91-9345678901",
    source: "Organic",
    courseInterest: "B.Tech Cyber Security",
    campus: "COIMBATORE",
    school: "Subbaraya Matric HSS, Kancheepuram",
    district: "Kancheepuram",
    state: "Tamil Nadu",
    address: "11 Gandhi Road, Kancheepuram 631501",
    status: "ADMITTED",
    createdAt: "2026-08-03T16:45:00Z",
    application: {
      id: "app_216",
      leadId: "lead_116",
      stage: "FEE_PAID",
      marks10th: 93.0,
      marks12th: 95.8,
      paymentStatus: "COMPLETED",
    },
  },
  {
    id: "lead_117",
    name: "T. Saravanan",
    email: "saravanan.t@gmail.com",
    phone: "+91-9234567890",
    source: "College Expo",
    courseInterest: "B.E Civil Engineering",
    campus: "KARUR",
    school: "Schaffter Higher Sec School, Tirunelveli",
    district: "Tirunelveli",
    state: "Tamil Nadu",
    address: "89 High Ground, Palayamkottai, Tirunelveli 627002",
    status: "CONTACTED",
    createdAt: "2026-08-03T10:10:00Z",
    application: {
      id: "app_217",
      leadId: "lead_117",
      stage: "SUBMITTED",
      marks10th: 81.2,
      marks12th: 83.4,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_118",
    name: "P. Yogesh",
    email: "yogesh.p@gmail.com",
    phone: "+91-9123456789",
    source: "Facebook Ads",
    courseInterest: "B.E. Computer Science and Engineering",
    campus: "KARUR",
    school: "St. Josephs HSS, Cuddalore",
    district: "Cuddalore",
    state: "Tamil Nadu",
    address: "44 Beach Road, Cuddalore 607001",
    status: "IN_REVIEW",
    createdAt: "2026-08-02T14:00:00Z",
    application: {
      id: "app_218",
      leadId: "lead_118",
      stage: "DOCS_VERIFIED",
      marks10th: 86.8,
      marks12th: 89.2,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_119",
    name: "S. Swetha",
    email: "swetha.s@gmail.com",
    phone: "+91-9012345678",
    source: "TNEA Counselling",
    courseInterest: "B.Tech Artificial Intelligence and Data Science",
    campus: "COIMBATORE",
    school: "Govt Girls HSS, Dharmapuri",
    district: "Dharmapuri",
    state: "Tamil Nadu",
    address: "16 Salem Main Road, Dharmapuri 636701",
    status: "NEW",
    createdAt: "2026-08-02T09:30:00Z",
    application: {
      id: "app_219",
      leadId: "lead_119",
      stage: "INQUIRY",
      marks10th: 91.5,
      marks12th: 93.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_120",
    name: "V. Balamurugan",
    email: "balamurugan.v@gmail.com",
    phone: "+91-8901234567",
    source: "Referral",
    courseInterest: "B.E Mechanical Engineering",
    campus: "KARUR",
    school: "NSKP HSS, Theni",
    district: "Theni",
    state: "Tamil Nadu",
    address: "27 Periyakulam Road, Theni 625531",
    status: "CONTACTED",
    createdAt: "2026-08-01T16:15:00Z",
    application: {
      id: "app_220",
      leadId: "lead_120",
      stage: "SUBMITTED",
      marks10th: 83.5,
      marks12th: 85.0,
      paymentStatus: "PENDING",
    },
  },
];

export const MOCK_TODAYS_TASKS: Task[] = [
  {
    id: "tsk_301",
    counselorId: "usr_admin_vsb",
    leadId: "lead_102",
    title: "Verify 12th Cutoff & Scholarship Marks for Coimbatore Campus",
    type: "CALL",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_102",
      name: "P. Ananya",
      phone: "+91 97654 32109",
      email: "ananya.p@outlook.com",
      courseInterest: "B.Tech AI & Data Science",
    },
  },
  {
    id: "tsk_302",
    counselorId: "usr_admin_vsb",
    leadId: "lead_104",
    title: "Send Allotment Letter & Hostel Fee Details for VSB Coimbatore",
    type: "EMAIL",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_104",
      name: "R. Priyadarshini",
      phone: "+91 95432 10987",
      email: "priya.r@techmail.in",
      courseInterest: "B.Tech Information Technology",
    },
  },
  {
    id: "tsk_303",
    counselorId: "usr_admin_vsb",
    leadId: "lead_103",
    title: "Follow up on Campus Tour confirmation for Karur Campus",
    type: "WHATSAPP",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_103",
      name: "M. Karthik",
      phone: "+91 96543 21098",
      email: "karthik.m@yahoo.com",
      courseInterest: "B.E. Electronics & Communication",
    },
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "pay_401",
    applicationId: "app_201",
    studentName: "S. Vignesh",
    course: "B.E. Computer Science",
    campus: "KARUR",
    amount: 85000,
    status: "COMPLETED",
    transactionId: "VSB_TXN_998827361",
    createdAt: "2026-08-01T15:00:00Z",
  },
  {
    id: "pay_402",
    applicationId: "app_207",
    studentName: "G. Hariharan",
    course: "B.E. Computer Science",
    campus: "COIMBATORE",
    amount: 95000,
    status: "COMPLETED",
    transactionId: "VSB_TXN_998827362",
    createdAt: "2026-08-05T09:00:00Z",
  },
];
