import { User, Lead, Application, Task, Payment, Teacher } from "@/types/crm";

export const TAMIL_NADU_DISTRICTS = [
  "Ariyalur",
  "Chengalpattu",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kancheepuram",
  "Kanniyakumari",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Mayiladuthurai",
  "Nagapattinam",
  "Namakkal",
  "Nilgiris",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Ranipet",
  "Salem",
  "Sivaganga",
  "Tenkasi",
  "Thanjavur",
  "Theni",
  "Thoothukudi",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Vellore",
  "Viluppuram",
  "Virudhunagar",
];

export const MOCK_ADMIN_USER: User = {
  id: "usr_admin_vsb",
  name: "VSB Admission Admin",
  email: "admin@vsb",
  role: "ADMIN",
  createdAt: new Date().toISOString(),
};

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: "tch_101",
    name: "Dr. K. Arulmurugan",
    email: "arulmurugan.cse@vsb.ac.in",
    phone: "+91 98424 11223",
    department: "Computer Science & Engineering",
    campus: "KARUR",
    coursesAssigned: ["B.E. Computer Science", "B.Tech AI & Data Science"],
    experienceYears: 14,
    status: "ACTIVE",
    avatar: "KA",
    assignedQuota: 1000,
    contactedCount: 142,
  },
  {
    id: "tch_102",
    name: "Dr. S. Meenakshi",
    email: "meenakshi.ece@vsb.ac.in",
    phone: "+91 97888 22334",
    department: "Electronics & Communication Engg",
    campus: "COIMBATORE",
    coursesAssigned: ["B.E. Electronics & Communication", "B.Tech Cyber Security"],
    experienceYears: 11,
    status: "ACTIVE",
    avatar: "SM",
    assignedQuota: 1000,
    contactedCount: 215,
  },
  {
    id: "tch_103",
    name: "Prof. P. Rajesh",
    email: "rajesh.mech@vsb.ac.in",
    phone: "+91 99433 33445",
    department: "Mechanical Engineering",
    campus: "KARUR",
    coursesAssigned: ["B.E. Mechanical Engineering"],
    experienceYears: 16,
    status: "ACTIVE",
    avatar: "PR",
    assignedQuota: 500,
    contactedCount: 88,
  },
  {
    id: "tch_104",
    name: "Dr. N. Gayathri",
    email: "gayathri.it@vsb.ac.in",
    phone: "+91 98655 44556",
    department: "Information Technology",
    campus: "COIMBATORE",
    coursesAssigned: ["B.Tech Information Technology"],
    experienceYears: 9,
    status: "ON_LEAVE",
    avatar: "NG",
    assignedQuota: 500,
    contactedCount: 64,
  },
];

export const MOCK_LEADS: (Lead & { application: Application })[] = [
  {
    id: "lead_jaikaviesh",
    name: "Jaikaviesh",
    email: "priya11092008@gmail.com",
    phone: "+91-9629693794",
    fatherName: "K. Ramachandran",
    motherName: "R. Priya",
    gender: "Male",
    bloodGroup: "O+",
    physicallyDisabled: "No",
    community: "BC",
    source: "Organic",
    courseInterest: "UG",
    campus: "KARUR",
    school: "Govt Higher Secondary School, Salem",
    district: "Salem",
    state: "Tamil Nadu",
    address: "14 West Car Street, Salem, Tamil Nadu 636001",
    status: "NEW",
    subStage: "Asked to Call Back",
    leadScore: 5,
    counselorId: "usr_admin_vsb",
    assignedTo: "Dr Dhanabal M Assistant Professor MECH",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-670B5",
    tneaCutoff: 188.5,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 3120,
    createdAt: "2026-08-12T11:38:00Z",
    application: {
      id: "app_jaikaviesh",
      leadId: "lead_jaikaviesh",
      stage: "INQUIRY",
      marks10th: 92.0,
      marks12th: 94.2,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_revathy",
    name: "Revathy",
    email: "revathy@gmail.com",
    phone: "+91-9566207732",
    source: "Organic",
    courseInterest: "B.E. Computer Science and Engineering",
    campus: "KARUR",
    state: "State Not Available",
    district: "Karur",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_revathy",
      leadId: "lead_revathy",
      stage: "INQUIRY",
      marks10th: 88.0,
      marks12th: 90.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_wilsonrani",
    name: "Wilsonrani789",
    email: "priya11092008@gmail.com",
    phone: "+91-9585228382",
    source: "Organic",
    courseInterest: "B.Tech Information Technology",
    campus: "COIMBATORE",
    state: "State Not Available",
    district: "Coimbatore",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_wilsonrani",
      leadId: "lead_wilsonrani",
      stage: "INQUIRY",
      marks10th: 85.0,
      marks12th: 87.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_gunal",
    name: "Gunal",
    email: "gunal@gmail.com",
    phone: "+91-9551082291",
    source: "Organic",
    courseInterest: "B.E Mechanical Engineering",
    campus: "KARUR",
    state: "State Not Available",
    district: "Karur",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_gunal",
      leadId: "lead_gunal",
      stage: "INQUIRY",
      marks10th: 82.0,
      marks12th: 84.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_manivel",
    name: "Manivel",
    email: "manivel@gmail.com",
    phone: "+91-8883158493",
    source: "Organic",
    courseInterest: "B.E Electrical and Electronics Engineering",
    campus: "KARUR",
    state: "State Not Available",
    district: "Karur",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_manivel",
      leadId: "lead_manivel",
      stage: "INQUIRY",
      marks10th: 80.0,
      marks12th: 83.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_sankari",
    name: "Sankari",
    email: "sankari@gmail.com",
    phone: "+91-9790181878",
    source: "Organic",
    courseInterest: "B.Tech Artificial Intelligence and Data Science",
    campus: "COIMBATORE",
    state: "State Not Available",
    district: "Coimbatore",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_sankari",
      leadId: "lead_sankari",
      stage: "INQUIRY",
      marks10th: 90.0,
      marks12th: 92.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_rajpriyan",
    name: "Raj Priyan",
    email: "rajpriyan@gmail.com",
    phone: "+91-9894283561",
    source: "Organic",
    courseInterest: "B.E Electronics and Communication Engineering",
    campus: "KARUR",
    state: "State Not Available",
    district: "Karur",
    status: "NEW",
    createdAt: "2026-08-12T11:40:00Z",
    application: {
      id: "app_rajpriyan",
      leadId: "lead_rajpriyan",
      stage: "INQUIRY",
      marks10th: 89.0,
      marks12th: 91.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_101",
    name: "S. Vignesh",
    email: "vignesh.s@gmail.com",
    phone: "+91 98765 43210",
    source: "TNEA Counselling",
    courseInterest: "B.E. Computer Science",
    campus: "KARUR",
    school: "Govt Higher Secondary School, Karur",
    district: "Karur",
    address: "42 West Car Street, Karur Town, Tamil Nadu 639001",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61201",
    tneaCutoff: 194.5,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 2840,
    createdAt: "2026-08-01T10:15:00Z",
    application: {
      id: "app_201",
      leadId: "lead_101",
      stage: "FEE_PAID",
      marks10th: 94.5,
      marks12th: 96.8,
      paymentStatus: "COMPLETED",
    },
  },
  {
    id: "lead_102",
    name: "P. Ananya",
    email: "ananya.p@outlook.com",
    phone: "+91 97654 32109",
    source: "Management Quota Direct",
    courseInterest: "B.Tech AI & Data Science",
    campus: "COIMBATORE",
    school: "St. Joseph Higher Secondary School, Coimbatore",
    district: "Coimbatore",
    address: "108 Trichy Road, Singanallur, Coimbatore 641005",
    status: "IN_REVIEW",
    counselorId: "usr_admin_vsb",
    assignedTo: "teachercovai@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-71409",
    tneaCutoff: 187.0,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 5120,
    createdAt: "2026-08-02T14:30:00Z",
    application: {
      id: "app_202",
      leadId: "lead_102",
      stage: "DOCS_VERIFIED",
      marks10th: 91.0,
      marks12th: 93.2,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_103",
    name: "M. Karthik",
    email: "karthik.m@yahoo.com",
    phone: "+91 96543 21098",
    source: "College Expo Salem",
    courseInterest: "B.E. Electronics & Communication",
    campus: "KARUR",
    school: "Sri Vidya Mandir Higher Sec School, Salem",
    district: "Salem",
    address: "15 Fairlands Main Road, Salem 636016",
    status: "CONTACTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61244",
    tneaCutoff: 176.5,
    counsellingCategory: "7.5% Govt School Quota",
    generalRank: 9410,
    createdAt: "2026-08-03T09:00:00Z",
    application: {
      id: "app_203",
      leadId: "lead_103",
      stage: "SUBMITTED",
      marks10th: 85.4,
      marks12th: 88.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_104",
    name: "R. Priyadarshini",
    email: "priya.r@techmail.in",
    phone: "+91 95432 10987",
    source: "Official VSB Portal",
    courseInterest: "B.Tech Information Technology",
    campus: "COIMBATORE",
    school: "Holy Cross Higher Sec School, Tiruchirappalli",
    district: "Tiruchirappalli",
    address: "88 Cantonment Main Street, Trichy 620001",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teachercovai@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-71422",
    tneaCutoff: 195.0,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 1950,
    createdAt: "2026-08-03T11:45:00Z",
    application: {
      id: "app_204",
      leadId: "lead_104",
      stage: "OFFER_ISSUED",
      marks10th: 96.0,
      marks12th: 97.5,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_105",
    name: "K. Tamilselvan",
    email: "tamil.k@gmail.com",
    phone: "+91 94321 09876",
    source: "TNEA Referral",
    courseInterest: "B.E. Mechanical Engineering",
    campus: "KARUR",
    school: "Govt Boys Model HSS, Namakkal",
    district: "Namakkal",
    address: "24 Mohanur Road, Namakkal 637001",
    status: "NEW",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61299",
    tneaCutoff: 169.0,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 14200,
    createdAt: "2026-08-04T16:20:00Z",
    application: {
      id: "app_205",
      leadId: "lead_105",
      stage: "INQUIRY",
      marks10th: 82.0,
      marks12th: 84.5,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_106",
    name: "S. Kaviya",
    email: "kaviya.s@domain.com",
    phone: "+91 93210 98765",
    source: "Newspaper Ad",
    courseInterest: "B.Tech Cyber Security",
    campus: "COIMBATORE",
    school: "Kongu Vellalar Matric HSS, Erode",
    district: "Erode",
    address: "67 Perundurai Road, Erode 638011",
    status: "IN_REVIEW",
    counselorId: "usr_admin_vsb",
    appliedCounselling: false,
    counsellingCategory: "Management Quota Direct",
    tneaCutoff: 182.2,
    createdAt: "2026-08-04T17:10:00Z",
    application: {
      id: "app_206",
      leadId: "lead_106",
      stage: "DOCS_VERIFIED",
      marks10th: 89.2,
      marks12th: 91.1,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_107",
    name: "G. Hariharan",
    email: "hari.g@outlook.com",
    phone: "+91 92109 87654",
    source: "TNEA Counselling",
    courseInterest: "B.E. Computer Science",
    campus: "COIMBATORE",
    school: "TVS Higher Secondary School, Madurai",
    district: "Madurai",
    address: "12 Subramaniapuram 1st Street, Madurai 625011",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-71450",
    tneaCutoff: 193.8,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 3110,
    createdAt: "2026-08-05T08:30:00Z",
    application: {
      id: "app_207",
      leadId: "lead_107",
      stage: "FEE_PAID",
      marks10th: 95.1,
      marks12th: 96.8,
      paymentStatus: "COMPLETED",
    },
  },
  {
    id: "lead_108",
    name: "A. Balaji",
    email: "balaji.a@gmail.com",
    phone: "+91 91098 76543",
    source: "College Expo Salem",
    courseInterest: "B.E Civil Engineering",
    campus: "KARUR",
    school: "Govt Boys Higher Sec School, Salem",
    district: "Salem",
    address: "45 Junction Road, Salem 636005",
    status: "REJECTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61311",
    tneaCutoff: 142.0,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 24500,
    createdAt: "2026-08-06T11:20:00Z",
    application: {
      id: "app_208",
      leadId: "lead_108",
      stage: "INQUIRY",
      marks10th: 71.0,
      marks12th: 71.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_109",
    name: "N. Dharshini",
    email: "dharshini.n@gmail.com",
    phone: "+91 90987 65432",
    source: "TNEA Counselling",
    courseInterest: "B.Tech Artificial Intelligence and Data Science",
    campus: "KARUR",
    school: "Paramathi Velur HSS, Namakkal",
    district: "Namakkal",
    address: "18 Main Road, Paramathi Velur, Namakkal 638182",
    status: "NEW",
    counselorId: "usr_admin_vsb",
    assignedTo: "teacherkarur@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-61380",
    tneaCutoff: 191.2,
    counsellingCategory: "7.5% Govt School Quota",
    generalRank: 4120,
    createdAt: "2026-08-07T09:10:00Z",
    application: {
      id: "app_209",
      leadId: "lead_109",
      stage: "INQUIRY",
      marks10th: 93.5,
      marks12th: 95.6,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_110",
    name: "V. Gokulakrishnan",
    email: "gokul.v@outlook.com",
    phone: "+91 89876 54321",
    source: "Official VSB Portal",
    courseInterest: "B.E Electronics and Communication Engineering",
    campus: "COIMBATORE",
    school: "Bharathi Matric HSS, Coimbatore",
    district: "Coimbatore",
    address: "55 Avinashi Road, Peelamedu, Coimbatore 641004",
    status: "CONTACTED",
    counselorId: "usr_admin_vsb",
    assignedTo: "teachercovai@123",
    appliedCounselling: true,
    counsellingAppNo: "TNEA2026-71488",
    tneaCutoff: 188.5,
    counsellingCategory: "TNEA General Counselling",
    generalRank: 4890,
    createdAt: "2026-08-08T14:45:00Z",
    application: {
      id: "app_210",
      leadId: "lead_110",
      stage: "SUBMITTED",
      marks10th: 90.0,
      marks12th: 94.2,
      paymentStatus: "PENDING",
    },
  },
];

const generateLeadsForAll38Districts = (): (Lead & { application: Application })[] => {
  const extraLeads: (Lead & { application: Application })[] = [];
  
  const sampleFirstNames = [
    "Arun", "Bala", "Chandran", "Deepak", "Elango", "Farook", "Gokul", "Hari",
    "Iniyan", "Jeevitha", "Kavya", "Latha", "Manoj", "Naveen", "Oviya", "Praveen",
    "Qadir", "Ramesh", "Sangeetha", "Tamilselvan", "Udhaya", "Vimal", "Wasim", "Yashwanth", "Zainab",
    "Anand", "Dinesh", "Karthik", "Madhavan", "Nandhini", "Pavithra", "Saravanan", "Thamarai", "Vijay", "Yuvraj"
  ];
  
  const sampleLastNames = [
    "Kumar", "Rajan", "Senthil", "Murugan", "Devi", "Priya", "Velan", "Nathan",
    "Ganesan", "Sundaram", "Subramanian", "Kannan", "Pandian", "Moorthy"
  ];

  const courses = [
    "B.E. Computer Science and Engineering",
    "B.Tech Artificial Intelligence and Data Science",
    "B.Tech Information Technology",
    "B.E. Electronics and Communication Engineering",
    "B.E Electrical and Electronics Engineering",
    "B.E Mechanical Engineering",
  ];

  TAMIL_NADU_DISTRICTS.forEach((district, index) => {
    for (let i = 1; i <= 2; i++) {
      const fName = sampleFirstNames[(index * 2 + i) % sampleFirstNames.length];
      const lName = sampleLastNames[(index * 3 + i) % sampleLastNames.length];
      const leadId = `lead_dist_${district.toLowerCase().replace(/\s+/g, "")}_${i}`;

      extraLeads.push({
        id: leadId,
        name: `${fName} ${lName}`,
        email: `${fName.toLowerCase()}.${lName.toLowerCase()}${index + 10}@vsbstudent.in`,
        phone: `+91-${9412300000 + index * 100 + i * 7}`,
        fatherName: `${lName} M`,
        motherName: `S. ${fName}ammal`,
        gender: i % 2 === 0 ? "Female" : "Male",
        community: i % 3 === 0 ? "BC" : i % 3 === 1 ? "MBC" : "OC",
        source: i % 2 === 0 ? "Organic" : "TNEA Counselling",
        courseInterest: courses[(index + i) % courses.length],
        campus: index % 2 === 0 ? "KARUR" : "COIMBATORE",
        school: `Govt Higher Secondary School, ${district}`,
        district: district,
        state: "Tamil Nadu",
        address: `${10 + i * 5} Main Road, ${district}, Tamil Nadu`,
        status: i === 1 ? "NEW" : "CONTACTED",
        leadScore: 8 + (index % 3),
        counselorId: "usr_admin_vsb",
        assignedTo: index % 2 === 0 ? "adminkarur@123" : "admincovai@123",
        appliedCounselling: true,
        counsellingAppNo: `TNEA2026-${district.substring(0, 3).toUpperCase()}${100 + i}`,
        tneaCutoff: 175 + (index % 20) + (i * 0.5),
        counsellingCategory: "TNEA General Counselling",
        generalRank: 1500 + index * 120 + i * 15,
        createdAt: `2026-08-12T10:${10 + i}:00Z`,
        application: {
          id: `app_dist_${district.toLowerCase().replace(/\s+/g, "")}_${i}`,
          leadId: leadId,
          stage: i === 1 ? "INQUIRY" : "DOCS_VERIFIED",
          marks10th: 85 + (index % 12),
          marks12th: 88 + (index % 10),
          paymentStatus: "PENDING",
        },
      });
    }
  });

  return extraLeads;
};

// Combine Base Mock Leads with All 38 District Student Records
export const MOCK_LEADS_ALL = [...MOCK_LEADS, ...generateLeadsForAll38Districts()];

export const MOCK_TODAYS_TASKS: Task[] = [
  {
    id: "tsk_301",
    counselorId: "usr_admin_vsb",
    leadId: "lead_102",
    title: "Verify 12th Cutoff & Scholarship Marks for Coimbatore Campus",
    type: "CALL",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_102",
      name: "P. Ananya",
      phone: "+91 97654 32109",
      email: "ananya.p@outlook.com",
      courseInterest: "B.Tech AI & Data Science",
    },
  },
  {
    id: "tsk_302",
    counselorId: "usr_admin_vsb",
    leadId: "lead_104",
    title: "Send Allotment Letter & Hostel Fee Details for VSB Coimbatore",
    type: "EMAIL",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_104",
      name: "R. Priyadarshini",
      phone: "+91 95432 10987",
      email: "priya.r@techmail.in",
      courseInterest: "B.Tech Information Technology",
    },
  },
  {
    id: "tsk_303",
    counselorId: "usr_admin_vsb",
    leadId: "lead_103",
    title: "Follow up on Campus Tour confirmation for Karur Campus",
    type: "WHATSAPP",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_103",
      name: "M. Karthik",
      phone: "+91 96543 21098",
      email: "karthik.m@yahoo.com",
      courseInterest: "B.E. Electronics & Communication",
    },
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "pay_401",
    applicationId: "app_201",
    studentName: "S. Vignesh",
    course: "B.E. Computer Science",
    campus: "KARUR",
    amount: 85000,
    status: "COMPLETED",
    transactionId: "VSB_TXN_998827361",
    createdAt: "2026-08-01T15:00:00Z",
  },
  {
    id: "pay_402",
    applicationId: "app_207",
    studentName: "G. Hariharan",
    course: "B.E. Computer Science",
    campus: "COIMBATORE",
    amount: 95000,
    status: "COMPLETED",
    transactionId: "VSB_TXN_998827362",
    createdAt: "2026-08-05T09:00:00Z",
  },
];
