import { User, Lead, Application, Task, Payment, Teacher } from "@/types/crm";

export const MOCK_ADMIN_USER: User = {
  id: "usr_admin_vsb",
  name: "VSB Admission Admin",
  email: "admin@vsb",
  role: "ADMIN",
  createdAt: new Date().toISOString(),
};

export const MOCK_TEACHERS: Teacher[] = [
  {
    id: "tch_101",
    name: "Dr. K. Arulmurugan",
    email: "arulmurugan.cse@vsb.ac.in",
    phone: "+91 98424 11223",
    department: "Computer Science & Engineering",
    campus: "KARUR",
    coursesAssigned: ["B.E. Computer Science", "B.Tech AI & Data Science"],
    experienceYears: 14,
    status: "ACTIVE",
    avatar: "KA",
  },
  {
    id: "tch_102",
    name: "Dr. S. Meenakshi",
    email: "meenakshi.ece@vsb.ac.in",
    phone: "+91 97888 22334",
    department: "Electronics & Communication Engg",
    campus: "COIMBATORE",
    coursesAssigned: ["B.E. Electronics & Communication", "B.Tech Cyber Security"],
    experienceYears: 11,
    status: "ACTIVE",
    avatar: "SM",
  },
  {
    id: "tch_103",
    name: "Prof. P. Rajesh",
    email: "rajesh.mech@vsb.ac.in",
    phone: "+91 99433 33445",
    department: "Mechanical Engineering",
    campus: "KARUR",
    coursesAssigned: ["B.E. Mechanical Engineering"],
    experienceYears: 16,
    status: "ACTIVE",
    avatar: "PR",
  },
  {
    id: "tch_104",
    name: "Dr. N. Gayathri",
    email: "gayathri.it@vsb.ac.in",
    phone: "+91 98655 44556",
    department: "Information Technology",
    campus: "COIMBATORE",
    coursesAssigned: ["B.Tech Information Technology"],
    experienceYears: 9,
    status: "ON_LEAVE",
    avatar: "NG",
  },
];

export const MOCK_LEADS: (Lead & { application: Application })[] = [
  {
    id: "lead_101",
    name: "S. Vignesh",
    email: "vignesh.s@gmail.com",
    phone: "+91 98765 43210",
    source: "TNEA Counselling",
    courseInterest: "B.E. Computer Science",
    campus: "KARUR",
    school: "Govt Higher Secondary School, Karur",
    district: "Karur",
    address: "42 West Car Street, Karur Town, Tamil Nadu 639001",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    createdAt: "2026-08-01T10:15:00Z",
    application: {
      id: "app_201",
      leadId: "lead_101",
      stage: "FEE_PAID",
      marks10th: 94.5,
      marks12th: 96.8,
      paymentStatus: "COMPLETED",
    },
  },
  {
    id: "lead_102",
    name: "P. Ananya",
    email: "ananya.p@outlook.com",
    phone: "+91 97654 32109",
    source: "Management Quota Direct",
    courseInterest: "B.Tech AI & Data Science",
    campus: "COIMBATORE",
    school: "St. Joseph Higher Secondary School, Coimbatore",
    district: "Coimbatore",
    address: "108 Trichy Road, Singanallur, Coimbatore 641005",
    status: "IN_REVIEW",
    counselorId: "usr_admin_vsb",
    createdAt: "2026-08-02T14:30:00Z",
    application: {
      id: "app_202",
      leadId: "lead_102",
      stage: "DOCS_VERIFIED",
      marks10th: 91.0,
      marks12th: 93.2,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_103",
    name: "M. Karthik",
    email: "karthik.m@yahoo.com",
    phone: "+91 96543 21098",
    source: "College Expo Salem",
    courseInterest: "B.E. Electronics & Communication",
    campus: "KARUR",
    school: "Sri Vidya Mandir Higher Sec School, Salem",
    district: "Salem",
    address: "15 Fairlands Main Road, Salem 636016",
    status: "CONTACTED",
    counselorId: "usr_admin_vsb",
    createdAt: "2026-08-03T09:00:00Z",
    application: {
      id: "app_203",
      leadId: "lead_103",
      stage: "SUBMITTED",
      marks10th: 85.4,
      marks12th: 88.0,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_104",
    name: "R. Priyadarshini",
    email: "priya.r@techmail.in",
    phone: "+91 95432 10987",
    source: "Official VSB Portal",
    courseInterest: "B.Tech Information Technology",
    campus: "COIMBATORE",
    school: "Holy Cross Higher Sec School, Tiruchirappalli",
    district: "Tiruchirappalli",
    address: "88 Cantonment Main Street, Trichy 620001",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    createdAt: "2026-08-03T11:45:00Z",
    application: {
      id: "app_204",
      leadId: "lead_104",
      stage: "OFFER_ISSUED",
      marks10th: 96.0,
      marks12th: 97.5,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_105",
    name: "K. Tamilselvan",
    email: "tamil.k@gmail.com",
    phone: "+91 94321 09876",
    source: "TNEA Referral",
    courseInterest: "B.E. Mechanical Engineering",
    campus: "KARUR",
    school: "Govt Boys Model HSS, Namakkal",
    district: "Namakkal",
    address: "24 Mohanur Road, Namakkal 637001",
    status: "NEW",
    counselorId: "usr_admin_vsb",
    createdAt: "2026-08-04T16:20:00Z",
    application: {
      id: "app_205",
      leadId: "lead_105",
      stage: "INQUIRY",
      marks10th: 82.0,
      marks12th: 84.5,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_106",
    name: "S. Kaviya",
    email: "kaviya.s@domain.com",
    phone: "+91 93210 98765",
    source: "Newspaper Ad",
    courseInterest: "B.Tech Cyber Security",
    campus: "COIMBATORE",
    school: "Kongu Vellalar Matric HSS, Erode",
    district: "Erode",
    address: "67 Perundurai Road, Erode 638011",
    status: "IN_REVIEW",
    counselorId: "usr_admin_vsb",
    createdAt: "2026-08-04T17:10:00Z",
    application: {
      id: "app_206",
      leadId: "lead_106",
      stage: "DOCS_VERIFIED",
      marks10th: 89.2,
      marks12th: 91.1,
      paymentStatus: "PENDING",
    },
  },
  {
    id: "lead_107",
    name: "G. Hariharan",
    email: "hari.g@outlook.com",
    phone: "+91 92109 87654",
    source: "TNEA Counselling",
    courseInterest: "B.E. Computer Science",
    campus: "COIMBATORE",
    school: "TVS Higher Secondary School, Madurai",
    district: "Madurai",
    address: "12 Subramaniapuram 1st Street, Madurai 625011",
    status: "ADMITTED",
    counselorId: "usr_admin_vsb",
    createdAt: "2026-08-05T08:30:00Z",
    application: {
      id: "app_207",
      leadId: "lead_107",
      stage: "FEE_PAID",
      marks10th: 95.1,
      marks12th: 96.8,
      paymentStatus: "COMPLETED",
    },
  },
];

export const MOCK_TODAYS_TASKS: Task[] = [
  {
    id: "tsk_301",
    counselorId: "usr_admin_vsb",
    leadId: "lead_102",
    title: "Verify 12th Cutoff & Scholarship Marks for Coimbatore Campus",
    type: "CALL",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_102",
      name: "P. Ananya",
      phone: "+91 97654 32109",
      email: "ananya.p@outlook.com",
      courseInterest: "B.Tech AI & Data Science",
    },
  },
  {
    id: "tsk_302",
    counselorId: "usr_admin_vsb",
    leadId: "lead_104",
    title: "Send Allotment Letter & Hostel Fee Details for VSB Coimbatore",
    type: "EMAIL",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_104",
      name: "R. Priyadarshini",
      phone: "+91 95432 10987",
      email: "priya.r@techmail.in",
      courseInterest: "B.Tech Information Technology",
    },
  },
  {
    id: "tsk_303",
    counselorId: "usr_admin_vsb",
    leadId: "lead_103",
    title: "Follow up on Campus Tour confirmation for Karur Campus",
    type: "WHATSAPP",
    dueDate: new Date().toISOString(),
    isCompleted: false,
    lead: {
      id: "lead_103",
      name: "M. Karthik",
      phone: "+91 96543 21098",
      email: "karthik.m@yahoo.com",
      courseInterest: "B.E. Electronics & Communication",
    },
  },
];

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: "pay_401",
    applicationId: "app_201",
    studentName: "S. Vignesh",
    course: "B.E. Computer Science",
    campus: "KARUR",
    amount: 85000,
    status: "COMPLETED",
    transactionId: "VSB_TXN_998827361",
    createdAt: "2026-08-01T15:00:00Z",
  },
  {
    id: "pay_402",
    applicationId: "app_207",
    studentName: "G. Hariharan",
    course: "B.E. Computer Science",
    campus: "COIMBATORE",
    amount: 95000,
    status: "COMPLETED",
    transactionId: "VSB_TXN_998827362",
    createdAt: "2026-08-05T09:00:00Z",
  },
];
